/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief UART 1 receive data source select: UART1_RX pin */
#define SOPT5_UART1RXSRC_UART_RX 0x00u
/*!
 * @brief UART 1 transmit data source select: UART1_TX pin */
#define SOPT5_UART1TXSRC_UART_TX 0x00u
/*!
 * @brief FTM0 channel 0 output source: FTM0_CH0 pin is output of FTM0 channel 0 output */
#define SOPT8_FTM0OCH0SRC_FTM 0x00u
/*!
 * @brief FTM0 channel 1 output source: FTM0_CH1 pin is output of FTM0 channel 1 output */
#define SOPT8_FTM0OCH1SRC_FTM 0x00u
/*!
 * @brief FTM0 channel 2 output source: FTM0_CH2 pin is output of FTM0 channel 2 output */
#define SOPT8_FTM0OCH2SRC_FTM 0x00u
/*!
 * @brief FTM0 channel 3 output source: FTM0_CH3 pin is output of FTM0 channel 3 output */
#define SOPT8_FTM0OCH3SRC_FTM 0x00u
/*!
 * @brief FTM0 channel 4 output source: FTM0_CH4 pin is output of FTM0 channel 4 output */
#define SOPT8_FTM0OCH4SRC_FTM 0x00u
/*!
 * @brief FTM0 channel 5 output source: FTM0_CH5 pin is output of FTM0 channel 5 output */
#define SOPT8_FTM0OCH5SRC_FTM 0x00u

/*! @name PORTE5 (number 6), test_pin
  @{ */
#define BOARD_INITPINS_test_pin_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_test_pin_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_test_pin_PIN 5U     /*!<@brief PORTE pin index: 5 */
                                           /* @} */

/*! @name PORTA1 (number 35), a1
  @{ */
#define BOARD_INITPINS_a1_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_a1_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_a1_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                     /* @} */

/*! @name PORTA2 (number 36), a2
  @{ */
#define BOARD_INITPINS_a2_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_a2_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_a2_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                     /* @} */

/*! @name PORTB18 (number 64), BST_CHNL_0
  @{ */
#define BOARD_INITPINS_BST_CHNL_0_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BST_CHNL_0_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BST_CHNL_0_PIN 18U    /*!<@brief PORTB pin index: 18 */
                                             /* @} */

/*! @name PORTB19 (number 65), BST_CHNL_1
  @{ */
#define BOARD_INITPINS_BST_CHNL_1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_BST_CHNL_1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_BST_CHNL_1_PIN 19U    /*!<@brief PORTB pin index: 19 */
                                             /* @} */

/*! @name PORTD0 (number 93), UH
  @{ */
#define BOARD_INITPINS_UH_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_UH_PIN 0U     /*!<@brief PORTD pin index: 0 */
                                     /* @} */

/*! @name PORTD1 (number 94), UL
  @{ */
#define BOARD_INITPINS_UL_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_UL_PIN 1U     /*!<@brief PORTD pin index: 1 */
                                     /* @} */

/*! @name PORTD2 (number 95), VH
  @{ */
#define BOARD_INITPINS_VH_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_VH_PIN 2U     /*!<@brief PORTD pin index: 2 */
                                     /* @} */

/*! @name PORTD3 (number 96), VL
  @{ */
#define BOARD_INITPINS_VL_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_VL_PIN 3U     /*!<@brief PORTD pin index: 3 */
                                     /* @} */

/*! @name PORTD4 (number 97), WH
  @{ */
#define BOARD_INITPINS_WH_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_WH_PIN 4U     /*!<@brief PORTD pin index: 4 */
                                     /* @} */

/*! @name PORTD5 (number 98), WL
  @{ */
#define BOARD_INITPINS_WL_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_WL_PIN 5U     /*!<@brief PORTD pin index: 5 */
                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
