/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v6.0
processor: MKV56F1M0xxx24
package_id: MKV56F1M0VLL24
mcu_data: ksdk2_0
processor_version: 6.0.1
pin_labels:
- {pin_num: '93', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FTM0_CH0/FLEXPWM0_A0/FB_ALE/FB_CS1_b/FB_TS_b/FLEXPWM1_A0, label: UH, identifier: UH}
- {pin_num: '94', pin_signal: HSADC1A_CH11/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FTM0_CH1/FLEXPWM0_B0/FB_CS0_b/FLEXPWM1_B0, label: UL, identifier: UL;idc}
- {pin_num: '95', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FTM0_CH2/FLEXPWM0_A1/I2C0_SCL/FB_AD4/FLEXPWM1_A1, label: VH, identifier: VH}
- {pin_num: '96', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FTM0_CH3/FLEXPWM0_B1/I2C0_SDA/FB_AD3/FLEXPWM1_B1, label: VL, identifier: VL}
- {pin_num: '97', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FLEXPWM0_A2/EWM_IN/SPI1_PCS0/FB_AD2, label: WH, identifier: WH}
- {pin_num: '98', pin_signal: HSADC1A_CH8/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FLEXPWM0_B2/EWM_OUT_b/SPI1_SCK/FB_AD1, label: WL, identifier: WL}
- {pin_num: '64', pin_signal: PTB18/CAN0_TX/FTM2_CH0/FTM3_CH2/FLEXPWM1_A1/FTM2_QD_PHA/FB_AD15, label: BST_CHNL_0, identifier: BST_CHNL_0}
- {pin_num: '65', pin_signal: PTB19/CAN0_RX/FTM2_CH1/FTM3_CH3/FLEXPWM1_B1/FTM2_QD_PHB/FB_OE_b, label: BST_CHNL_1, identifier: BST_CHNL_1}
- {pin_num: '6', pin_signal: HSADC1A_CH5/ADC0_SE10/ADC0_DM2/PTE5/SPI1_PCS2/UART3_RX/FLEXPWM1_A0/FTM3_CH0, label: test_pin, identifier: test_pin}
- {pin_num: '35', pin_signal: PTA1/UART0_RX/FTM0_CH6/CMP0_OUT/FTM2_QD_PHA/FTM1_CH1/JTAG_TDI, label: a1, identifier: a1}
- {pin_num: '36', pin_signal: PTA2/UART0_TX/FTM0_CH7/CMP1_OUT/FTM2_QD_PHB/FTM1_CH0/JTAG_TDO/TRACE_SWO, label: a2, identifier: a2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '10', peripheral: ADC0, signal: 'DP, 1', pin_signal: HSADC0A_CH0/ADC0_SE1/ADC0_DP1/PTE16/SPI0_PCS0/UART2_TX/FTM_CLKIN0/FTM0_FLT3}
  - {pin_num: '11', peripheral: ADC0, signal: 'DM, 1', pin_signal: HSADC0A_CH1/ADC0_SE9/ADC0_DM1/PTE17/LLWU_P19/SPI0_SCK/UART2_RX/FTM_CLKIN1/LPTMR0_ALT3}
  - {pin_num: '12', peripheral: HSADC0, signal: 'ADCB, CH0', pin_signal: HSADC0B_CH0/ADC0_SE5a/PTE18/LLWU_P20/SPI0_SOUT/UART2_CTS_b/I2C0_SDA}
  - {pin_num: '13', peripheral: HSADC0, signal: 'ADCB, CH1', pin_signal: HSADC0B_CH1/ADC0_SE6a/PTE19/SPI0_SIN/UART2_RTS_b/I2C0_SCL/CMP3_OUT}
  - {pin_num: '18', peripheral: HSADC0, signal: 'ADCA, CH2', pin_signal: HSADC0A_CH2/HSADC1A_CH2}
  - {pin_num: '19', peripheral: HSADC0, signal: 'ADCA, CH3', pin_signal: HSADC0A_CH3/HSADC1A_CH3}
  - {pin_num: '6', peripheral: GPIOE, signal: 'GPIO, 5', pin_signal: HSADC1A_CH5/ADC0_SE10/ADC0_DM2/PTE5/SPI1_PCS2/UART3_RX/FLEXPWM1_A0/FTM3_CH0, direction: OUTPUT}
  - {pin_num: '1', peripheral: UART1, signal: TX, pin_signal: HSADC0B_CH16/HSADC1A_CH0/PTE0/SPI1_PCS1/UART1_TX/XB_OUT10/XB_IN11/I2C1_SDA/TRACE_CLKOUT}
  - {pin_num: '2', peripheral: UART1, signal: RX, pin_signal: HSADC0B_CH17/HSADC1A_CH1/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/XB_OUT11/XB_IN7/I2C1_SCL/TRACE_D3}
  - {pin_num: '7', peripheral: GPIOE, signal: 'GPIO, 6', pin_signal: HSADC1B_CH7/ADC0_SE4a/PTE6/LLWU_P16/SPI1_PCS3/UART3_CTS_b/FLEXPWM1_B0/FTM3_CH1}
  - {pin_num: '26', peripheral: GPIOE, signal: 'GPIO, 29', pin_signal: HSADC0A_CH4/CMP1_IN5/CMP0_IN5/PTE29/FTM0_CH2/FTM_CLKIN0}
  - {pin_num: '27', peripheral: GPIOE, signal: 'GPIO, 30', pin_signal: DAC0_OUT/CMP1_IN3/HSADC0A_CH5/PTE30/FTM0_CH3/FTM_CLKIN1}
  - {pin_num: '35', peripheral: GPIOA, signal: 'GPIO, 1', pin_signal: PTA1/UART0_RX/FTM0_CH6/CMP0_OUT/FTM2_QD_PHA/FTM1_CH1/JTAG_TDI, direction: OUTPUT}
  - {pin_num: '36', peripheral: GPIOA, signal: 'GPIO, 2', pin_signal: PTA2/UART0_TX/FTM0_CH7/CMP1_OUT/FTM2_QD_PHB/FTM1_CH0/JTAG_TDO/TRACE_SWO, direction: OUTPUT}
  - {pin_num: '64', peripheral: GPIOB, signal: 'GPIO, 18', pin_signal: PTB18/CAN0_TX/FTM2_CH0/FTM3_CH2/FLEXPWM1_A1/FTM2_QD_PHA/FB_AD15, direction: OUTPUT}
  - {pin_num: '65', peripheral: GPIOB, signal: 'GPIO, 19', pin_signal: PTB19/CAN0_RX/FTM2_CH1/FTM3_CH3/FLEXPWM1_B1/FTM2_QD_PHB/FB_OE_b, direction: OUTPUT}
  - {pin_num: '90', peripheral: GPIOC, signal: 'GPIO, 16', pin_signal: PTC16/CAN1_RX/UART3_RX/FLEXPWM1_A2/FB_CS5_b/FB_TSIZ1/FB_BE23_16_b}
  - {pin_num: '91', peripheral: GPIOC, signal: 'GPIO, 17', pin_signal: PTC17/CAN1_TX/UART3_TX/FLEXPWM1_B2/FB_CS4_b/FB_TSIZ0/FB_BE31_24_b}
  - {pin_num: '39', peripheral: GPIOA, signal: 'GPIO, 5', pin_signal: PTA5/FTM0_CH2/CMP2_OUT/JTAG_TRST_b, direction: INPUT}
  - {pin_num: '42', peripheral: GPIOA, signal: 'GPIO, 12', pin_signal: CMP2_IN0/PTA12/CAN0_TX/FTM1_CH0/FTM1_QD_PHA/I2C0_SCL, direction: INPUT}
  - {pin_num: '43', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: CMP2_IN1/PTA13/LLWU_P4/CAN0_RX/FTM1_CH1/FTM1_QD_PHB/I2C1_SDA, direction: INPUT}
  - {pin_num: '44', peripheral: GPIOA, signal: 'GPIO, 14', pin_signal: CMP3_IN0/PTA14/SPI0_PCS0/UART0_TX/I2C1_SCL, direction: INPUT}
  - {pin_num: '53', peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: HSADC0B_CH2/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/FTM1_QD_PHA/UART0_RX, direction: INPUT}
  - {pin_num: '54', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: HSADC0B_CH3/PTB1/I2C0_SDA/FTM1_CH1/FTM0_FLT2/EWM_IN/FTM1_QD_PHB/UART0_TX, direction: INPUT}
  - {pin_num: '55', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: HSADC0A_CH14/CMP2_IN2/PTB2/I2C0_SCL/UART0_RTS_b/FTM0_FLT1/FTM0_FLT3, direction: INPUT}
  - {pin_num: '56', peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: HSADC0B_CH15/CMP3_IN5/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/FTM0_FLT0, direction: INPUT}
  - {pin_num: '93', peripheral: FTM0, signal: 'CH, 0', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FTM0_CH0/FLEXPWM0_A0/FB_ALE/FB_CS1_b/FB_TS_b/FLEXPWM1_A0,
    direction: OUTPUT}
  - {pin_num: '94', peripheral: FTM0, signal: 'CH, 1', pin_signal: HSADC1A_CH11/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FTM0_CH1/FLEXPWM0_B0/FB_CS0_b/FLEXPWM1_B0, identifier: UL,
    direction: OUTPUT}
  - {pin_num: '95', peripheral: FTM0, signal: 'CH, 2', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FTM0_CH2/FLEXPWM0_A1/I2C0_SCL/FB_AD4/FLEXPWM1_A1, direction: OUTPUT}
  - {pin_num: '96', peripheral: FTM0, signal: 'CH, 3', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FTM0_CH3/FLEXPWM0_B1/I2C0_SDA/FB_AD3/FLEXPWM1_B1, direction: OUTPUT}
  - {pin_num: '97', peripheral: FTM0, signal: 'CH, 4', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FLEXPWM0_A2/EWM_IN/SPI1_PCS0/FB_AD2, direction: OUTPUT}
  - {pin_num: '98', peripheral: FTM0, signal: 'CH, 5', pin_signal: HSADC1A_CH8/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FLEXPWM0_B2/EWM_OUT_b/SPI1_SCK/FB_AD1,
    direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t a1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA1 (pin 35)  */
    GPIO_PinInit(BOARD_INITPINS_a1_GPIO, BOARD_INITPINS_a1_PIN, &a1_config);

    gpio_pin_config_t a2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA2 (pin 36)  */
    GPIO_PinInit(BOARD_INITPINS_a2_GPIO, BOARD_INITPINS_a2_PIN, &a2_config);

    gpio_pin_config_t gpioa_pin39_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA5 (pin 39)  */
    GPIO_PinInit(GPIOA, 5U, &gpioa_pin39_config);

    gpio_pin_config_t gpioa_pin42_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA12 (pin 42)  */
    GPIO_PinInit(GPIOA, 12U, &gpioa_pin42_config);

    gpio_pin_config_t gpioa_pin43_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA13 (pin 43)  */
    GPIO_PinInit(GPIOA, 13U, &gpioa_pin43_config);

    gpio_pin_config_t gpioa_pin44_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA14 (pin 44)  */
    GPIO_PinInit(GPIOA, 14U, &gpioa_pin44_config);

    gpio_pin_config_t gpiob_pin53_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin 53)  */
    GPIO_PinInit(GPIOB, 0U, &gpiob_pin53_config);

    gpio_pin_config_t gpiob_pin54_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB1 (pin 54)  */
    GPIO_PinInit(GPIOB, 1U, &gpiob_pin54_config);

    gpio_pin_config_t gpiob_pin55_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin 55)  */
    GPIO_PinInit(GPIOB, 2U, &gpiob_pin55_config);

    gpio_pin_config_t gpiob_pin56_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin 56)  */
    GPIO_PinInit(GPIOB, 3U, &gpiob_pin56_config);

    gpio_pin_config_t BST_CHNL_0_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB18 (pin 64)  */
    GPIO_PinInit(BOARD_INITPINS_BST_CHNL_0_GPIO, BOARD_INITPINS_BST_CHNL_0_PIN, &BST_CHNL_0_config);

    gpio_pin_config_t BST_CHNL_1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB19 (pin 65)  */
    GPIO_PinInit(BOARD_INITPINS_BST_CHNL_1_GPIO, BOARD_INITPINS_BST_CHNL_1_PIN, &BST_CHNL_1_config);

    gpio_pin_config_t test_pin_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE5 (pin 6)  */
    GPIO_PinInit(BOARD_INITPINS_test_pin_GPIO, BOARD_INITPINS_test_pin_PIN, &test_pin_config);

    /* PORTA1 (pin 35) is configured as PTA1 */
    PORT_SetPinMux(BOARD_INITPINS_a1_PORT, BOARD_INITPINS_a1_PIN, kPORT_MuxAsGpio);

    /* PORTA12 (pin 42) is configured as PTA12 */
    PORT_SetPinMux(PORTA, 12U, kPORT_MuxAsGpio);

    /* PORTA13 (pin 43) is configured as PTA13 */
    PORT_SetPinMux(PORTA, 13U, kPORT_MuxAsGpio);

    /* PORTA14 (pin 44) is configured as PTA14 */
    PORT_SetPinMux(PORTA, 14U, kPORT_MuxAsGpio);

    /* PORTA2 (pin 36) is configured as PTA2 */
    PORT_SetPinMux(BOARD_INITPINS_a2_PORT, BOARD_INITPINS_a2_PIN, kPORT_MuxAsGpio);

    /* PORTA5 (pin 39) is configured as PTA5 */
    PORT_SetPinMux(PORTA, 5U, kPORT_MuxAsGpio);

    /* PORTB0 (pin 53) is configured as PTB0 */
    PORT_SetPinMux(PORTB, 0U, kPORT_MuxAsGpio);

    /* PORTB1 (pin 54) is configured as PTB1 */
    PORT_SetPinMux(PORTB, 1U, kPORT_MuxAsGpio);

    /* PORTB18 (pin 64) is configured as PTB18 */
    PORT_SetPinMux(BOARD_INITPINS_BST_CHNL_0_PORT, BOARD_INITPINS_BST_CHNL_0_PIN, kPORT_MuxAsGpio);

    /* PORTB19 (pin 65) is configured as PTB19 */
    PORT_SetPinMux(BOARD_INITPINS_BST_CHNL_1_PORT, BOARD_INITPINS_BST_CHNL_1_PIN, kPORT_MuxAsGpio);

    /* PORTB2 (pin 55) is configured as PTB2 */
    PORT_SetPinMux(PORTB, 2U, kPORT_MuxAsGpio);

    /* PORTB3 (pin 56) is configured as PTB3 */
    PORT_SetPinMux(PORTB, 3U, kPORT_MuxAsGpio);

    /* PORTC16 (pin 90) is configured as PTC16 */
    PORT_SetPinMux(PORTC, 16U, kPORT_MuxAsGpio);

    /* PORTC17 (pin 91) is configured as PTC17 */
    PORT_SetPinMux(PORTC, 17U, kPORT_MuxAsGpio);

    /* PORTD0 (pin 93) is configured as FTM0_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_UH_PORT, BOARD_INITPINS_UH_PIN, kPORT_MuxAlt5);

    /* PORTD1 (pin 94) is configured as FTM0_CH1 */
    PORT_SetPinMux(BOARD_INITPINS_UL_PORT, BOARD_INITPINS_UL_PIN, kPORT_MuxAlt5);

    /* PORTD2 (pin 95) is configured as FTM0_CH2 */
    PORT_SetPinMux(BOARD_INITPINS_VH_PORT, BOARD_INITPINS_VH_PIN, kPORT_MuxAlt5);

    /* PORTD3 (pin 96) is configured as FTM0_CH3 */
    PORT_SetPinMux(BOARD_INITPINS_VL_PORT, BOARD_INITPINS_VL_PIN, kPORT_MuxAlt5);

    /* PORTD4 (pin 97) is configured as FTM0_CH4 */
    PORT_SetPinMux(BOARD_INITPINS_WH_PORT, BOARD_INITPINS_WH_PIN, kPORT_MuxAlt4);

    /* PORTD5 (pin 98) is configured as FTM0_CH5 */
    PORT_SetPinMux(BOARD_INITPINS_WL_PORT, BOARD_INITPINS_WL_PIN, kPORT_MuxAlt4);

    /* PORTE0 (pin 1) is configured as UART1_TX */
    PORT_SetPinMux(PORTE, 0U, kPORT_MuxAlt3);

    /* PORTE1 (pin 2) is configured as UART1_RX */
    PORT_SetPinMux(PORTE, 1U, kPORT_MuxAlt3);

    /* PORTE16 (pin 10) is configured as ADC0_DP1 */
    PORT_SetPinMux(PORTE, 16U, kPORT_PinDisabledOrAnalog);

    /* PORTE17 (pin 11) is configured as ADC0_DM1 */
    PORT_SetPinMux(PORTE, 17U, kPORT_PinDisabledOrAnalog);

    /* PORTE18 (pin 12) is configured as HSADC0B_CH0 */
    PORT_SetPinMux(PORTE, 18U, kPORT_PinDisabledOrAnalog);

    /* PORTE19 (pin 13) is configured as HSADC0B_CH1 */
    PORT_SetPinMux(PORTE, 19U, kPORT_PinDisabledOrAnalog);

    /* PORTE29 (pin 26) is configured as PTE29 */
    PORT_SetPinMux(PORTE, 29U, kPORT_MuxAsGpio);

    /* PORTE30 (pin 27) is configured as PTE30 */
    PORT_SetPinMux(PORTE, 30U, kPORT_MuxAsGpio);

    /* PORTE5 (pin 6) is configured as PTE5 */
    PORT_SetPinMux(BOARD_INITPINS_test_pin_PORT, BOARD_INITPINS_test_pin_PIN, kPORT_MuxAsGpio);

    /* PORTE6 (pin 7) is configured as PTE6 */
    PORT_SetPinMux(PORTE, 6U, kPORT_MuxAsGpio);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART1TXSRC_MASK | SIM_SOPT5_UART1RXSRC_MASK)))

                  /* UART 1 transmit data source select: UART1_TX pin. */
                  | SIM_SOPT5_UART1TXSRC(SOPT5_UART1TXSRC_UART_TX)

                  /* UART 1 receive data source select: UART1_RX pin. */
                  | SIM_SOPT5_UART1RXSRC(SOPT5_UART1RXSRC_UART_RX));

    SIM->SOPT8 =
        ((SIM->SOPT8 &
          /* Mask bits to zero which are setting */
          (~(SIM_SOPT8_FTM0OCH0SRC_MASK | SIM_SOPT8_FTM0OCH1SRC_MASK | SIM_SOPT8_FTM0OCH2SRC_MASK | SIM_SOPT8_FTM0OCH3SRC_MASK | SIM_SOPT8_FTM0OCH4SRC_MASK | SIM_SOPT8_FTM0OCH5SRC_MASK)))

         /* FTM0 channel 0 output source: FTM0_CH0 pin is output of FTM0 channel 0 output. */
         | SIM_SOPT8_FTM0OCH0SRC(SOPT8_FTM0OCH0SRC_FTM)

         /* FTM0 channel 1 output source: FTM0_CH1 pin is output of FTM0 channel 1 output. */
         | SIM_SOPT8_FTM0OCH1SRC(SOPT8_FTM0OCH1SRC_FTM)

         /* FTM0 channel 2 output source: FTM0_CH2 pin is output of FTM0 channel 2 output. */
         | SIM_SOPT8_FTM0OCH2SRC(SOPT8_FTM0OCH2SRC_FTM)

         /* FTM0 channel 3 output source: FTM0_CH3 pin is output of FTM0 channel 3 output. */
         | SIM_SOPT8_FTM0OCH3SRC(SOPT8_FTM0OCH3SRC_FTM)

         /* FTM0 channel 4 output source: FTM0_CH4 pin is output of FTM0 channel 4 output. */
         | SIM_SOPT8_FTM0OCH4SRC(SOPT8_FTM0OCH4SRC_FTM)

         /* FTM0 channel 5 output source: FTM0_CH5 pin is output of FTM0 channel 5 output. */
         | SIM_SOPT8_FTM0OCH5SRC(SOPT8_FTM0OCH5SRC_FTM));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
